# Generated by Django 5.0.2 on 2024-04-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='index',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
    ]
