# Generated by Django 5.0.2 on 2024-04-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_course_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='clas',
            field=models.CharField(max_length=2),
        ),
    ]
