# Generated by Django 5.0.2 on 2024-04-14 21:39

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_task_clas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='upload',
            field=models.FileField(upload_to=blog.models.user_directory_path),
        ),
    ]
